version: '3.8'
x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: always #no, on-failure , always(default), unless-stopped 

services:
  db:
    image: mysql:8
    #"mysql_native_password" only for wordpress, usually don't need!
    #command: "--default-authetication-plugin=mysql_native_password" 
    <<: [*deploy-dev, *env_file, *restart]
    volumes:
      - db_data:/var/lib/mysql
    networks:
      backend:
        ipv4_address: 172.20.0.10
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-exemple}
      - MYSQL_USER=${MYSQL_USER:-app}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-very_strong}
      - MYSQL_ROOT_HOST="%" # it's very important!!!
  web:
    image: cr.yandex/crp1ap4beir88sv77pce/python-app
    depends_on: ["db"]
    <<: [*deploy-dev, *env_file, *restart]
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 5000:5000
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQL_USER:-app}
      - DB_PASSWORD=${MYSQL_PASSWORD:-very_strong}
      - DB_NAME=${MYSQL_DATABASE:-exemple}
volumes:
  db_data: {}

networks:
  bakend:
    driver: bridge

include:
  - proxy.yaml
